#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ShinobiStockChart.Droid.Resource", IsApplication=true)]

namespace ShinobiStockChart.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040007
			public const int change_indicator_decreasing = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int change_indicator_increasing = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int chart_axis = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int chart_background = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int chart_series1_area = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int chart_series1_area_low = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int chart_series1_line = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int chart_series2_line = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_edit = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int action_add_moving_average = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int chart = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout1 = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int moving_average_period = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int stock_list = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int symbolTextView = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int text_price = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int text_ticker = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MovingAveragePeriodDialogLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int StockChartActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int StockItemListViewRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int StockPriceListActivityLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int chart_action_bar_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
